services:
  kafka:
    container_name: kafka
    image: registry.cn-guangzhou.aliyuncs.com/joe/cp-kafka:7.7.8
    environment:
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_MESSAGE_TIMESTAMP_TYPE: CreateTime
    ports: ["9092:9092"]
    volumes: ["kafka-data:/var/lib/kafka/data"]
    networks: [log-net]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "kafka-broker-api-versions --bootstrap-server localhost:9092",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
  ollama:
    container_name: llm
    image: ollama/ollama:latest
    ports: ["11434:11434"]
    volumes: ["ollama-data:/root/.ollama"]
    command: ["serve"]
    deploy:
      resources:
        limits: { memory: 8G }
    networks: [log-net]
  vector:
    container_name: vector
    image: registry.cn-guangzhou.aliyuncs.com/joe/vector:0.55.X-distroless-libc
    volumes:
      - ./vector.yaml:/etc/vector/vector.yaml:ro
      - /run/systemd/journal/socket:/run/systemd/journal/socket:ro
      - /var/log/journal:/var/log/journal:ro
    networks: [log-net]
    depends_on:
      kafka:
        condition: service_healthy
  clickhouse:
    container_name: clickhouse
    image: registry.cn-guangzhou.aliyuncs.com/joe/clickhouse-server:latest-distroless
    environment:
      CLICKHOUSE_DB: log_ai
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    ports: ["8123:8123", "9000:9000"]
    volumes: ["ch-data:/var/lib/clickhouse"]
    networks: [log-net]
networks:
  log-net:
    driver: bridge
volumes:
  kafka-data:
  ollama-data:
  ch-data:
